version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      PORT: ${PORT}
      MODE_DEV: 'production'
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    container_name: app
    restart: unless-stopped
    ports:
      - $PORT:$PORT
